"use client";



// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React, { useState, useEffect } from "react";
import { Menu, X, Github, Twitter, Linkedin, Activity, BookOpen, PenTool, Mail, User, LogIn, LayoutDashboard, LogOut } from 'lucide-react';
// @ts-expect-error global import
import './globals.css';
import { useRouter, usePathname } from "next/navigation";
import Link from "next/link";
import { AIChat } from "@/components/AIChat";
import { AuthService } from "@/lib/auth";










const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const NAV_ITEMS = [
    { label: 'About', path: '/about', icon: User },
    { label: 'Blog', path: '/blog', icon: PenTool },
    { label: 'Research', path: '/research', icon: BookOpen },
    { label: 'Health', path: '/health', icon: Activity },
    { label: 'Contact', path: '/contact', icon: Mail },
  ];
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isAuthenticated, setIsAuthenticated] = useState(() => AuthService.isAuthenticated());
  const router = useRouter();
  const currentPath = usePathname();

  useEffect(() => {
    // Listen for auth changes
    const handleAuthChange = () => {
      setIsAuthenticated(AuthService.isAuthenticated());
    };
    window.addEventListener('auth-change', handleAuthChange);
    return () => window.removeEventListener('auth-change', handleAuthChange);
  }, []);

  // Close mobile menu on route change
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsMobileMenuOpen(false);
  }, [currentPath]);

  const handleLogout = () => {
    AuthService.logout();
    router.push('/');
  };



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-background text-zinc-300 font-sans selection:bg-zinc-800 selection:text-white flex flex-col">
          {/* Navigation */}
          <nav className="fixed top-0 left-0 right-0 z-40 bg-background/80 backdrop-blur-md border-b border-border">
            <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">

              {/* Logo / Name */}
              <Link href="/" className="text-xl font-bold text-white tracking-tight flex items-center gap-2 group">
                <div className="w-8 h-8 bg-white text-black rounded flex items-center justify-center font-bold text-lg group-hover:scale-110 transition-transform">E</div>
                <span className="hidden sm:inline">Emmanuel Uchenna</span>
              </Link>

              {/* Desktop Links */}
              <div className="hidden md:flex items-center gap-8">
                {NAV_ITEMS.map((item) => (
                  <Link
                    key={item.path}
                    href={item.path}
                    className={`text-sm font-medium transition-colors hover:text-white ${currentPath === item.path ? 'text-white' : 'text-zinc-500'}`}
                  >
                    {item.label}
                  </Link>
                ))}

                <div className="h-4 w-px bg-zinc-800 mx-2"></div>

                {/* Auth Links */}
                {isAuthenticated ? (
                  <div className="flex items-center gap-6">
                    <Link
                      href="/admin"
                      className="text-sm font-semibold text-white bg-zinc-800 px-3 py-1.5 rounded-full hover:bg-zinc-700 transition-colors flex items-center gap-2"
                    >
                      <LayoutDashboard className="w-3.5 h-3.5" />
                      Dashboard
                    </Link>
                    <button
                      onClick={handleLogout}
                      className="text-sm font-medium text-zinc-500 hover:text-red-400 transition-colors"
                      aria-label="Logout"
                    >
                      <LogOut className="w-4 h-4" />
                    </button>
                  </div>
                ) : (
                  <Link
                    href="/auth/login"
                    className={`text-sm font-medium transition-colors flex items-center gap-2 hover:text-white ${currentPath === '/auth/login' ? 'text-white' : 'text-zinc-500'}`}
                  >
                    <LogIn className="w-4 h-4" />
                    Login
                  </Link>
                )}
              </div>

              {/* Mobile Toggle */}
              <button
                className="md:hidden p-2 text-zinc-400 hover:text-white"
                onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              >
                {isMobileMenuOpen ? <X /> : <Menu />}
              </button>
            </div>

            {/* Mobile Menu */}
            {isMobileMenuOpen && (
              <div className="md:hidden absolute top-16 left-0 right-0 bg-background border-b border-border p-6 flex flex-col gap-4 animate-in slide-in-from-top-5 shadow-2xl">
                {NAV_ITEMS.map((item) => (
                  <Link
                    key={item.path}
                    href={item.path}
                    className={`flex items-center gap-3 text-lg font-medium p-2 rounded-lg transition-colors text-zinc-500 hover:text-zinc-300`}
                  >
                    <item.icon className="w-5 h-5" />
                    {item.label}
                  </Link>
                ))}

                <div className="h-px bg-zinc-800 my-2"></div>

                {isAuthenticated ? (
                  <>
                    <Link
                      href="/admin"
                      className="flex items-center gap-3 text-lg font-medium p-2 rounded-lg text-white bg-zinc-800"
                    >
                      <LayoutDashboard className="w-5 h-5" />
                      Dashboard
                    </Link>
                    <button
                      onClick={handleLogout}
                      className="flex items-center gap-3 text-lg font-medium p-2 rounded-lg text-red-400 hover:bg-zinc-900 w-full text-left"
                    >
                      <LogOut className="w-5 h-5" />
                      Sign Out
                    </button>
                  </>
                ) : (
                  <Link
                    href="/auth/login"
                    className="flex items-center gap-3 text-lg font-medium p-2 rounded-lg text-zinc-500 hover:text-white"
                  >
                    <LogIn className="w-5 h-5" />
                    Login
                  </Link>
                )}
              </div>
            )}
          </nav>

          {/* Main Content */}
          <main className="flex-grow pt-24 px-6 pb-20 max-w-6xl mx-auto w-full">
            {children}
          </main>

          {/* Footer */}
          <footer className="border-t border-border py-12 px-6 bg-background">
            <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
              <div className="text-zinc-500 text-sm">
                © {new Date().getFullYear()} Emmanuel Uchenna. All rights reserved.
              </div>

              <div className="flex items-center gap-6">
                <a href="#" className="text-zinc-500 hover:text-white transition-colors" aria-label="GitHub">
                  <Github className="w-5 h-5" />
                </a>
                <a href="#" className="text-zinc-500 hover:text-white transition-colors" aria-label="Twitter">
                  <Twitter className="w-5 h-5" />
                </a>
                <a href="#" className="text-zinc-500 hover:text-white transition-colors" aria-label="LinkedIn">
                  <Linkedin className="w-5 h-5" />
                </a>
              </div>
            </div>
          </footer>

          <AIChat />
        </div>
      </body>
    </html>
  );
}
